### PR TITLE
cache Composer files on Travis CI between builds

### PR DESCRIPTION
**Pull request by xabbuh**

### CODE REVIEW

**Comment by lyrixx** [comment]
:+1:

**Comment by xabbuh** [comment]
@lyrixx Hm, I am not sure if this change is not related to the failing tests (I am bit too unfamiliar with what all the tests do). What do you think?

**Comment by lyrixx** [comment]
I'm on holidays, will check on Monday :-)

**Comment by ogizanagi** [comment]
@xabbuh : None of the failing tests are related to your changes. That's only due to Github's API rate limit and gists download.
We should probably create a user and token for those integration tests to work once #66 is ready.

**Comment by lyrixx** [comment]
Thank you @xabbuh.

**Pull request merged**
