### PR TITLE
Disable xdebug to speedup travis build

### PR DESCRIPTION
**Pull request by staabm**

### CODE REVIEW

**Comment by lyrixx** [comment]
:+1:

**Comment by lyrixx** [comment]
Why don't you use this [syntax](https://github.com/symfony/symfony/blob/master/.travis.yml#L64)?

**Comment by staabm** [comment]
> Why don't you use this syntax?

I dont work on the hhvm build

**Comment by xabbuh** [comment]
@staabm That's weird. Even if you replace `$PHP` with `$TRAVIS_PHP_VERSION`?

**Comment by staabm** [comment]
Hhvm does not use phpenv. In case we would add it we would need 2 separate cases, one for hhvm one for php to make it not fail.

**Comment by xabbuh** [comment]
@staabm But there's no Xdebug on HHVM to disable anyway, is there?

**Comment by staabm** [comment]
Dont know. The PR as is - is the simplest solution I guess. No unnecessary if etc.

**Comment by jderusse** [comment]
The comment of @lyrixx refer to the `phpenv config-rm` and not HHVM

**Comment by lyrixx** [comment]
Thank you @staabm.

**Pull request merged**
