### PR TITLE
Support composer like package notations

### LINKED ISSUE #76: support composer like notations
atm one needs to write

```
<<<CONFIG
packages:
    - "codeguy/arachnid: 1.*"
CONFIG;
```

for melody to get it working.

More composer like would be something like 

```
<<<CONFIG
packages:
    - "codeguy/arachnid": "1.*"
CONFIG;
```

as this is 1:1 the notation composer uses on CLI. this might semantically not be the JSON one would expect, but syntax wise it would be great, as you can pickup the lines from the composer.json

related to https://github.com/sensiolabs/melody/pull/75

### PR DESCRIPTION
**Pull request by staabm**
Fixes #76.

### CODE REVIEW

**Comment by lyrixx** [comment]
Could you add a test to ensure theses syntaxt work: (a least the first one)

 ```
packages:
    symfony/finder
    symfony/console: ~2.3
    "symfony/yaml: #2.3"
```

**Comment by staabm** [comment]
@lyrixx the code you posted is not valid json, is it?

**Comment by lyrixx** [comment]
Yes, indeed it's not valid ;) Sorry.

Could you update the doc to show the new syntax ?

**Comment by staabm** [comment]
do you think we should mention the alternative syntax or should it be the new primary syntax?

if primiary, someone needs to update the animated gif in the README.

**Comment by lyrixx** [comment]
I think it's better to show only the new one. And for the gif, we will see later :-)

**Comment by lyrixx** [comment]
@staabm Could you finish this one?!

**Comment by fabpot** [comment]
I'm going to archive this project now to make it clear that the project is not maintained anymore. Anyone can fork it.

**Pull request closed without merging**
